# Generated by Django 2.2.2 on 2019-10-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20190922_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Placed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USN', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('department', models.CharField(choices=[('ISE', 'ISE'), ('CSE', 'CSE'), ('ECE', 'ECE'), ('MEC', 'MEC'), ('CIV', 'CIV'), ('MBA', 'MBA'), ('MCA', 'MCA')], max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('company', models.CharField(max_length=80)),
                ('package', models.CharField(max_length=20)),
            ],
        ),
    ]
