# Generated by Django 2.2.2 on 2019-09-22 11:21

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('USN', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('department', models.CharField(choices=[('ISE', 'ISE'), ('CSE', 'CSE'), ('ECE', 'ECE'), ('MEC', 'MEC'), ('CIV', 'CIV'), ('MBA', 'MBA'), ('MCA', 'MCA')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('status', models.CharField(choices=[('inactive', 'inactive'), ('active', 'active')], default='active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BE_Student_Marks',
            fields=[
                ('USN', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='student.Student')),
                ('SSLC_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('PUC_or_diploma', models.CharField(choices=[('PUC', 'PUC'), ('Diploma', 'Diploma')], default='PUC', max_length=10)),
                ('PUC_or_diploma_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('CGPA', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='MBA_Student_Marks',
            fields=[
                ('USN', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='student.Student')),
                ('SSLC_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('PUC_or_diploma', models.CharField(choices=[('PUC', 'PUC'), ('Diploma', 'Diploma')], default='PUC', max_length=10)),
                ('PUC_or_diploma_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('BBA_or_BCOM', models.CharField(choices=[('BCOM', 'BCOM'), ('BBA', 'BBA')], default='BBA', max_length=10)),
                ('Finance_or_Management', models.CharField(choices=[('Finance', 'Finance'), ('Management', 'Management')], default='Finance', max_length=10)),
                ('BBA_or_BCOM_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('CGPA', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='MCA_Student_Marks',
            fields=[
                ('USN', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='student.Student')),
                ('SSLC_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('PUC_or_diploma', models.CharField(choices=[('PUC', 'PUC'), ('Diploma', 'Diploma')], default='PUC', max_length=10)),
                ('PUC_or_diploma_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('BCA_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('CGPA', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
            ],
        ),
    ]
