# Generated by Django 2.2.2 on 2019-09-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='last_edited_by',
            field=models.CharField(default='registered', max_length=50),
        ),
    ]
