# Generated by Django 2.2.2 on 2019-10-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_last_edited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='placements_mitm', max_length=50),
        ),
    ]
