# Generated by Django 2.2.2 on 2019-09-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=257)),
                ('department', models.CharField(choices=[('Placement', 'Placement'), ('ISE', 'ISE'), ('CSE', 'CSE'), ('ECE', 'ECE'), ('MEC', 'MEC'), ('CIV', 'CIV'), ('MBA', 'MBA'), ('MCA', 'MCA')], max_length=10)),
                ('user_type', models.CharField(choices=[('admin', 'admin'), ('co-ordinator', 'co-ordinator'), ('other', 'other')], default='co-ordinator', max_length=20)),
            ],
        ),
    ]
