# Generated by Django 2.2.2 on 2019-10-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinator_edit_student_details', models.BooleanField(default=True)),
                ('students_edit_their_details', models.BooleanField(default=False)),
            ],
        ),
    ]
