# Generated by Django 2.2.2 on 2019-10-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_permissions',
            name='add_students_to_company',
            field=models.BooleanField(default=False),
        ),
    ]
