# Generated by Django 2.2.2 on 2019-10-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_permissions_add_students_to_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_permissions',
            name='registration_open',
            field=models.BooleanField(default=True),
        ),
    ]
